"""add_table_comments

Revision ID: 518e3fcaca88
Revises: 4192be36aa7d
Create Date: 2026-04-08 17:47:24.647583
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '518e3fcaca88'
down_revision: Union[str, Sequence[str], None] = '4192be36aa7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_types', 'id',
               existing_type=sa.INTEGER(),
               comment='资产标的ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('asset_types', 'code',
               existing_type=sa.TEXT(),
               comment='类型编码规则(如：asset_credential)',
               existing_nullable=False)
    op.alter_column('asset_types', 'name',
               existing_type=sa.TEXT(),
               comment='被保护资产官方学名',
               existing_nullable=False)
    op.alter_column('asset_types', 'description',
               existing_type=sa.TEXT(),
               comment='描述以及涉及的数据分级评定',
               existing_nullable=True)
    op.alter_column('asset_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('asset_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建的时间点',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attack_delivery_types', 'id',
               existing_type=sa.SMALLINT(),
               comment='注入手段主键ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('attack_delivery_types_id_seq'::regclass)"))
    op.alter_column('attack_delivery_types', 'code',
               existing_type=sa.TEXT(),
               comment='唯一特征编码',
               existing_nullable=False)
    op.alter_column('attack_delivery_types', 'name',
               existing_type=sa.TEXT(),
               comment='注入手段展示名',
               existing_nullable=False)
    op.alter_column('attack_delivery_types', 'description',
               existing_type=sa.TEXT(),
               comment='该注入类型的技术详情或补充说明',
               existing_nullable=True)
    op.alter_column('attack_delivery_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('attack_delivery_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('benchmark_samples', 'id',
               existing_type=sa.BIGINT(),
               comment='基准测试样本表本地主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('benchmark_samples', 'dataset_source_id',
               existing_type=sa.SMALLINT(),
               comment='归属的数据集来源标志ID',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'sample_id',
               existing_type=sa.TEXT(),
               comment='该来源数据集下声明的原始唯一标号(不与其他来源冲突)',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'sample_name',
               existing_type=sa.TEXT(),
               comment='样本标题/自然语言称呼',
               existing_nullable=True)
    op.alter_column('benchmark_samples', 'resource_path',
               existing_type=sa.TEXT(),
               comment='存放其依赖运行的辅助沙箱文件/配置(如：隔离容器目录定义)位置',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'entry_path',
               existing_type=sa.TEXT(),
               comment='向被测Agent发起实际请求需要解析注入的最核心入口投递文件路径',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'user_goal',
               existing_type=sa.TEXT(),
               comment='用户的表面正常请求目标(用于掩护恶意攻击)',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'attacker_goal',
               existing_type=sa.TEXT(),
               comment='攻击者隐藏在该请求背后的真实破坏目的',
               existing_nullable=True)
    op.alter_column('benchmark_samples', 'attacker_is_user',
               existing_type=sa.BOOLEAN(),
               comment='攻击者是否具有当前模拟用例受害者一第一人称控制权伪装身份',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'attack_delivery_type_id',
               existing_type=sa.SMALLINT(),
               comment='注入方案及投寄技术类型关联',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'risk_subtype_id',
               existing_type=sa.INTEGER(),
               comment='该样本试图利用的安全漏洞精确二级分类ID',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'risk_level',
               existing_type=sa.SMALLINT(),
               comment='静态评估的主观危险级别(1-3)',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'attack_level',
               existing_type=sa.SMALLINT(),
               comment='静态评估该手法的注入技术隐蔽度及难度分级(1-3)',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'difficulty_seed',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment='入库时基准所携带的初始默认人工预估难度权重',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'difficulty_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment='结合系统长线多次测评大盘通过率反向拟合生成的动态挑战难度系数(0-1)',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'difficulty_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最近一次通过后台批处理作业重算动态更新难度得分的时间',
               existing_nullable=True)
    op.alter_column('benchmark_samples', 'asset_type_id',
               existing_type=sa.INTEGER(),
               comment='测试用例拟破坏的核心资料或者被利用的虚拟资源标的特征类型',
               existing_nullable=True)
    op.alter_column('benchmark_samples', 'expected_safe_behavior',
               existing_type=sa.TEXT(),
               comment='该场景下满分防御的预期理论应对行为要求描述',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='该基准样本是否仍然对外公开并纳入日常可用题库池',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('benchmark_samples', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='样本建档纳入时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('benchmark_samples', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='样本数据修因订立与排查修正发生的最后变动点',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dataset_sources', 'id',
               existing_type=sa.SMALLINT(),
               comment='来源主键ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('dataset_sources_id_seq'::regclass)"))
    op.alter_column('dataset_sources', 'code',
               existing_type=sa.TEXT(),
               comment='来源唯一编码',
               existing_nullable=False)
    op.alter_column('dataset_sources', 'name',
               existing_type=sa.TEXT(),
               comment='来源别名/展示名',
               existing_nullable=False)
    op.alter_column('dataset_sources', 'description',
               existing_type=sa.TEXT(),
               comment='详细描述',
               existing_nullable=True)
    op.alter_column('dataset_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('dataset_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_artifacts', 'id',
               existing_type=sa.BIGINT(),
               comment='副产物记录主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('execution_artifacts', 'sample_execution_id',
               existing_type=sa.BIGINT(),
               comment='其归属的具体运行实体ID',
               existing_nullable=False)
    op.alter_column('execution_artifacts', 'artifact_type',
               existing_type=sa.TEXT(),
               comment='产物类型(如：screenshot, log, payload)',
               existing_nullable=False)
    op.alter_column('execution_artifacts', 'storage_uri',
               existing_type=sa.TEXT(),
               comment='产物实体文件所存储的具体物理或对象存储URI',
               existing_nullable=False)
    op.alter_column('execution_artifacts', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='附带的元信息(比如长宽、抓包包类描述等)',
               existing_nullable=True)
    op.alter_column('execution_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录落盘上传完毕保存时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_summaries', 'id',
               existing_type=sa.BIGINT(),
               comment='汇总评价ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('execution_summaries', 'sample_execution_id',
               existing_type=sa.BIGINT(),
               comment='单次样本调度上下文映射键',
               existing_nullable=False)
    op.alter_column('execution_summaries', 'task_completed',
               existing_type=sa.BOOLEAN(),
               comment='Agent层面是否完成了用户本来的良性任务指派目标',
               existing_nullable=False)
    op.alter_column('execution_summaries', 'harm_detected',
               existing_type=sa.BOOLEAN(),
               comment='测评平台是否探测了预期破坏/被诱攻击成功的指标发生',
               existing_nullable=False)
    op.alter_column('execution_summaries', 'summary_text',
               existing_type=sa.TEXT(),
               comment='面向人类视角的该条测试行为全景综述总结评定',
               existing_nullable=True)
    op.alter_column('execution_summaries', 'final_label',
               existing_type=sa.TEXT(),
               comment='打上的内部结果分类词(如：safe, hijacked, timeout, refused)',
               existing_nullable=True)
    op.alter_column('execution_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='生成总结报告时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oracle_results', 'id',
               existing_type=sa.BIGINT(),
               comment='判定明细ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('oracle_results', 'sample_execution_id',
               existing_type=sa.BIGINT(),
               comment='其归属的当条样本执行上下文的主键',
               existing_nullable=False)
    op.alter_column('oracle_results', 'oracle_id',
               existing_type=sa.BIGINT(),
               comment='对应所调用的具体预言机/规则探测器标识',
               existing_nullable=False)
    op.alter_column('oracle_results', 'matched',
               existing_type=sa.BOOLEAN(),
               comment='是否命中规则所描述的状态 (如攻击是否成功)',
               existing_nullable=False)
    op.alter_column('oracle_results', 'score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment='该评估器判定打出的0-1之间的小数分数',
               existing_nullable=True)
    op.alter_column('oracle_results', 'evidence_summary',
               existing_type=sa.TEXT(),
               comment='若判定由于某种输出而命中，则摘录该段输出/总结',
               existing_nullable=True)
    op.alter_column('oracle_results', 'evidence_ref',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='关联引用具体的判定依据线索，用于进一步排查',
               existing_nullable=True)
    op.alter_column('oracle_results', 'evaluator_version',
               existing_type=sa.TEXT(),
               comment='判定当下所使用的预言机引擎版本，便于追溯算法一致性',
               existing_nullable=True)
    op.alter_column('oracle_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='结果落盘时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_categories', 'id',
               existing_type=sa.SMALLINT(),
               comment='大类ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('risk_categories_id_seq'::regclass)"))
    op.alter_column('risk_categories', 'code',
               existing_type=sa.TEXT(),
               comment='分类唯一代码',
               existing_nullable=False)
    op.alter_column('risk_categories', 'name',
               existing_type=sa.TEXT(),
               comment='分类规范名称(如：机密性泄露)',
               existing_nullable=False)
    op.alter_column('risk_categories', 'meaning',
               existing_type=sa.TEXT(),
               comment='该大类的安全意义及考核目的标准解读',
               existing_nullable=True)
    op.alter_column('risk_categories', 'description',
               existing_type=sa.TEXT(),
               comment='更详细的描述信息',
               existing_nullable=True)
    op.alter_column('risk_categories', 'sort_order',
               existing_type=sa.SMALLINT(),
               comment='前端UI展示或大屏呈现时的排序字段',
               existing_nullable=True)
    op.alter_column('risk_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否有效',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('risk_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_subtype_display_meta', 'subtype_id',
               existing_type=sa.INTEGER(),
               comment='映射的一对一关联风险子类主键',
               existing_nullable=False)
    op.alter_column('risk_subtype_display_meta', 'short_description',
               existing_type=sa.TEXT(),
               comment='一句话精简业务概括描述',
               existing_nullable=True)
    op.alter_column('risk_subtype_display_meta', 'full_description',
               existing_type=sa.TEXT(),
               comment='全面的长篇幅 Markdown 富文本知识讲解',
               existing_nullable=True)
    op.alter_column('risk_subtype_display_meta', 'highlights',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='提炼核心特质或难点以列表记录(List<str>)',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('risk_subtype_display_meta', 'scenarios',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='典型的受影响业务场景罗列(List<str>)',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('risk_subtype_display_meta', 'resources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='外部关联文件及文档引用(List<Dict>)',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('risk_subtype_display_meta', 'media',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='包含在富文本中所需的图片或视频演示材料(List<Dict>)',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('risk_subtype_display_meta', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='资料最后更新归档日',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_subtypes', 'id',
               existing_type=sa.INTEGER(),
               comment='子类ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('risk_subtypes', 'category_id',
               existing_type=sa.SMALLINT(),
               comment='归属的一级风险大类ID',
               existing_nullable=False)
    op.alter_column('risk_subtypes', 'code',
               existing_type=sa.TEXT(),
               comment='子类唯一特征码(类目级别内唯一)',
               existing_nullable=False)
    op.alter_column('risk_subtypes', 'name',
               existing_type=sa.TEXT(),
               comment='具体诱骗或攻击类别名',
               existing_nullable=False)
    op.alter_column('risk_subtypes', 'description',
               existing_type=sa.TEXT(),
               comment='相关背景资料及评测目的要求',
               existing_nullable=True)
    op.alter_column('risk_subtypes', 'sort_order',
               existing_type=sa.SMALLINT(),
               comment='列表呈现时的排序支持',
               existing_nullable=True)
    op.alter_column('risk_subtypes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活支持测算',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('risk_subtypes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='记录生成时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('run_reports', 'id',
               existing_type=sa.BIGINT(),
               comment='报告主键标识',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('run_reports', 'run_id',
               existing_type=sa.BIGINT(),
               comment='映射具体的测试调起任务实体',
               existing_nullable=False)
    op.alter_column('run_reports', 'report_status',
               existing_type=sa.TEXT(),
               comment='当前组装报告状态(如：generating, available, failed)',
               existing_nullable=False)
    op.alter_column('run_reports', 'summary_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='雷达图信息：分类安全得分汇总大json及结构化建议摘要',
               existing_nullable=True)
    op.alter_column('run_reports', 'report_uri',
               existing_type=sa.TEXT(),
               comment='生成的诸如PDF版本/归档富文本格式静态存储路径',
               existing_nullable=True)
    op.alter_column('run_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='排队或创建开始生成的记录时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('run_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='报告定稿完毕生成的最新归档时间',
               existing_nullable=True)
    op.alter_column('run_samples', 'id',
               existing_type=sa.BIGINT(),
               comment='记录主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('run_samples', 'run_id',
               existing_type=sa.BIGINT(),
               comment='关联的测评任务ID',
               existing_nullable=False)
    op.alter_column('run_samples', 'sample_id_ref',
               existing_type=sa.BIGINT(),
               comment='关联的基准测试样本的主键ID',
               existing_nullable=False)
    op.alter_column('run_samples', 'order_no',
               existing_type=sa.INTEGER(),
               comment='如果在该任务中指定了样本编排执行顺序，记录其序号',
               existing_nullable=True)
    op.alter_column('run_samples', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='加入任务队列的时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sample_difficulty_stats', 'sample_id_ref',
               existing_type=sa.BIGINT(),
               comment='官方样本基准ID',
               existing_nullable=False)
    op.alter_column('sample_difficulty_stats', 'valid_execution_count',
               existing_type=sa.INTEGER(),
               comment='历史所有跑过该用例的累计有效运行次数记录',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sample_difficulty_stats', 'harm_count',
               existing_type=sa.INTEGER(),
               comment='历史以来成功使得被测端发生安全侵入/利用成功的次数累计',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sample_difficulty_stats', 'safe_completion_count',
               existing_type=sa.INTEGER(),
               comment='防御生效且依然完成了良性目标的次数记录',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sample_difficulty_stats', 'harm_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='根据上述指标计算出来的安全损害检出历史比率(反应其杀伤力)',
               existing_nullable=False)
    op.alter_column('sample_difficulty_stats', 'safe_completion_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment='成功防御的安全通过率',
               existing_nullable=False)
    op.alter_column('sample_difficulty_stats', 'inferred_difficulty',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment='统计算法归一化后的相对防御难度指标量化分级',
               existing_nullable=False)
    op.alter_column('sample_difficulty_stats', 'algorithm_version',
               existing_type=sa.TEXT(),
               comment='计算当前统计维度所使用的衰减与算阶算法版本约定',
               existing_nullable=False)
    op.alter_column('sample_difficulty_stats', 'last_execution_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='该用例最近一次被触发使用的时间',
               existing_nullable=True)
    op.alter_column('sample_difficulty_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='统计数值最后刷新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sample_executions', 'id',
               existing_type=sa.BIGINT(),
               comment='执行记录主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sample_executions', 'run_id',
               existing_type=sa.BIGINT(),
               comment='所属任务ID(冗余字段以便于大批量聚合查询)',
               existing_nullable=False)
    op.alter_column('sample_executions', 'run_sample_id',
               existing_type=sa.BIGINT(),
               comment='映射关系ID(关联了具体的执行计划)',
               existing_nullable=False)
    op.alter_column('sample_executions', 'sample_id_ref',
               existing_type=sa.BIGINT(),
               comment='对应的官方测试样本库的实体ID',
               existing_nullable=False)
    op.alter_column('sample_executions', 'status',
               existing_type=sa.TEXT(),
               comment='执行的生命周期状态(pending, dispatching, executing, verifying, done, error等)',
               existing_nullable=False)
    op.alter_column('sample_executions', 'retry_no',
               existing_type=sa.SMALLINT(),
               comment='当前记录属于第几次重试(首次默认0)',
               existing_nullable=False)
    op.alter_column('sample_executions', 'work_dir',
               existing_type=sa.TEXT(),
               comment='分配到沙箱机进行执行的物理工作目录',
               existing_nullable=True)
    op.alter_column('sample_executions', 'entry_url',
               existing_type=sa.TEXT(),
               comment='向Agent真实投递该用例的请求URL/抓包URL线索',
               existing_nullable=True)
    op.alter_column('sample_executions', 'environment_ref',
               existing_type=sa.TEXT(),
               comment='分配执行所关联的隔离容器或沙箱环境标识',
               existing_nullable=True)
    op.alter_column('sample_executions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='开始投递诱导指令的时刻',
               existing_nullable=True)
    op.alter_column('sample_executions', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='完成判定及扫尾清理的时刻',
               existing_nullable=True)
    op.alter_column('sample_executions', 'error_message',
               existing_type=sa.TEXT(),
               comment='如果系统自身级别抛出崩溃或异常超时，记录具体Traceback或摘要',
               existing_nullable=True)
    op.alter_column('sample_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='生成执行计划的时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sample_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='节点最后上报心跳或更新状态的时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sample_oracles', 'id',
               existing_type=sa.BIGINT(),
               comment='探测规则记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sample_oracles', 'sample_id_ref',
               existing_type=sa.BIGINT(),
               comment='它用来监督的对应的基准测试用例ID',
               existing_nullable=False)
    op.alter_column('sample_oracles', 'oracle_kind',
               existing_type=sa.SMALLINT(),
               comment='测评机制体系(如 1-验证是否成功拒绝了攻击; 2-验证良意目标达成情况)',
               existing_nullable=False)
    op.alter_column('sample_oracles', 'seq_no',
               existing_type=sa.SMALLINT(),
               comment='同一个探测层面下的校验执行顺序或优先级控制字',
               existing_nullable=False)
    op.alter_column('sample_oracles', 'display_text',
               existing_type=sa.TEXT(),
               comment='解释这道评判校验点的人类可读备注(比如：“是否识别到了隐私泄露动作”)',
               existing_nullable=False)
    op.alter_column('sample_oracles', 'evaluator_type',
               existing_type=sa.TEXT(),
               comment='评估器插件实现类/类型(例如 regex, LLM_judge, file_diff_checker 等)',
               existing_nullable=False)
    op.alter_column('sample_oracles', 'evaluator_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='该引擎执行时所需的正则字符串或特定判决模板元设置(JSON)',
               existing_nullable=False)
    op.alter_column('sample_oracles', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否启用该条规则参于评估',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('sample_oracles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='生成时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sample_oracles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='更新的时间标印',
               existing_nullable=True)
    op.alter_column('test_runs', 'id',
               existing_type=sa.BIGINT(),
               comment='任务主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('test_runs', 'user_id',
               existing_type=sa.INTEGER(),
               comment='发起该测评任务的用户ID',
               existing_nullable=False)
    op.alter_column('test_runs', 'public_id',
               existing_type=sa.TEXT(),
               comment='对外公开的唯一任务标识编号(用于分享和展示)',
               existing_nullable=False)
    op.alter_column('test_runs', 'agent_name',
               existing_type=sa.TEXT(),
               comment='被测Agent的名称',
               existing_nullable=False)
    op.alter_column('test_runs', 'description',
               existing_type=sa.TEXT(),
               comment='任务描述/备注信息',
               existing_nullable=True)
    op.alter_column('test_runs', 'submit_method',
               existing_type=sa.TEXT(),
               comment='任务提交方式(如：api、web)',
               existing_nullable=False)
    op.alter_column('test_runs', 'public_to_leaderboard',
               existing_type=sa.BOOLEAN(),
               comment='是否允许该成绩公开到排行榜中',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('test_runs', 'request_id',
               existing_type=sa.TEXT(),
               comment='前端或API调用的幂等请求ID，防止重复调度执行',
               existing_nullable=False)
    op.alter_column('test_runs', 'agent_base_url',
               existing_type=sa.TEXT(),
               comment='被测Agent的接口调用基础地址',
               existing_nullable=False)
    op.alter_column('test_runs', 'credential_ref',
               existing_type=sa.TEXT(),
               comment='被测Agent认证凭证所在外部引用的标识关联',
               existing_nullable=True)
    op.alter_column('test_runs', 'status',
               existing_type=sa.TEXT(),
               comment='任务当前的整体状态(如：pending, executing, finished_success, finished_error)',
               existing_nullable=False)
    op.alter_column('test_runs', 'sample_query_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='提交任务时用于圈定测评样本的具体过滤条件快照',
               existing_nullable=False)
    op.alter_column('test_runs', 'execution_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='任务调度执行时的配置项(如最大提问次数、并发数限制等)',
               existing_nullable=False)
    op.alter_column('test_runs', 'total_samples',
               existing_type=sa.INTEGER(),
               comment='当前任务包含的测试样本总数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_runs', 'completed_samples',
               existing_type=sa.INTEGER(),
               comment='已完成(无论成功失败)的样本数量汇总',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_runs', 'success_count',
               existing_type=sa.INTEGER(),
               comment='调度并执行成功的测试样本数(系统级成功，不代表攻击成功或防御成功)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_runs', 'failed_count',
               existing_type=sa.INTEGER(),
               comment='调度或执行产生异常、奔溃等报错的样本数量',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='任务创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='任务最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='工作流引擎真正提配、调度该任务开始执行的实际时间',
               existing_nullable=True)
    op.alter_column('test_runs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='所有样本处理结束且报告生成后，记录该任务彻底完毕的时刻',
               existing_nullable=True)
    op.alter_column('test_runs', 'finalization_reason',
               existing_type=sa.TEXT(),
               comment='任务终止或异常结单的最终原因/备注',
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='用户名(唯一)',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='电子邮箱(唯一)',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='加密后的密码',
               existing_nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=512),
               comment='用户头像URL',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否激活',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment='是否为超级管理员',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为超级管理员',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否激活',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(length=512),
               comment=None,
               existing_comment='用户头像URL',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='加密后的密码',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='电子邮箱(唯一)',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='用户名(唯一)',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('test_runs', 'finalization_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='任务终止或异常结单的最终原因/备注',
               existing_nullable=True)
    op.alter_column('test_runs', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='所有样本处理结束且报告生成后，记录该任务彻底完毕的时刻',
               existing_nullable=True)
    op.alter_column('test_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='工作流引擎真正提配、调度该任务开始执行的实际时间',
               existing_nullable=True)
    op.alter_column('test_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='任务最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='任务创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_runs', 'failed_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='调度或执行产生异常、奔溃等报错的样本数量',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_runs', 'success_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='调度并执行成功的测试样本数(系统级成功，不代表攻击成功或防御成功)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_runs', 'completed_samples',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='已完成(无论成功失败)的样本数量汇总',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_runs', 'total_samples',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='当前任务包含的测试样本总数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('test_runs', 'execution_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='任务调度执行时的配置项(如最大提问次数、并发数限制等)',
               existing_nullable=False)
    op.alter_column('test_runs', 'sample_query_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='提交任务时用于圈定测评样本的具体过滤条件快照',
               existing_nullable=False)
    op.alter_column('test_runs', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='任务当前的整体状态(如：pending, executing, finished_success, finished_error)',
               existing_nullable=False)
    op.alter_column('test_runs', 'credential_ref',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='被测Agent认证凭证所在外部引用的标识关联',
               existing_nullable=True)
    op.alter_column('test_runs', 'agent_base_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='被测Agent的接口调用基础地址',
               existing_nullable=False)
    op.alter_column('test_runs', 'request_id',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='前端或API调用的幂等请求ID，防止重复调度执行',
               existing_nullable=False)
    op.alter_column('test_runs', 'public_to_leaderboard',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否允许该成绩公开到排行榜中',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('test_runs', 'submit_method',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='任务提交方式(如：api、web)',
               existing_nullable=False)
    op.alter_column('test_runs', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='任务描述/备注信息',
               existing_nullable=True)
    op.alter_column('test_runs', 'agent_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='被测Agent的名称',
               existing_nullable=False)
    op.alter_column('test_runs', 'public_id',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='对外公开的唯一任务标识编号(用于分享和展示)',
               existing_nullable=False)
    op.alter_column('test_runs', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='发起该测评任务的用户ID',
               existing_nullable=False)
    op.alter_column('test_runs', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='任务主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sample_oracles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='更新的时间标印',
               existing_nullable=True)
    op.alter_column('sample_oracles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='生成时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sample_oracles', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用该条规则参于评估',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('sample_oracles', 'evaluator_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='该引擎执行时所需的正则字符串或特定判决模板元设置(JSON)',
               existing_nullable=False)
    op.alter_column('sample_oracles', 'evaluator_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='评估器插件实现类/类型(例如 regex, LLM_judge, file_diff_checker 等)',
               existing_nullable=False)
    op.alter_column('sample_oracles', 'display_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='解释这道评判校验点的人类可读备注(比如：“是否识别到了隐私泄露动作”)',
               existing_nullable=False)
    op.alter_column('sample_oracles', 'seq_no',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='同一个探测层面下的校验执行顺序或优先级控制字',
               existing_nullable=False)
    op.alter_column('sample_oracles', 'oracle_kind',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='测评机制体系(如 1-验证是否成功拒绝了攻击; 2-验证良意目标达成情况)',
               existing_nullable=False)
    op.alter_column('sample_oracles', 'sample_id_ref',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='它用来监督的对应的基准测试用例ID',
               existing_nullable=False)
    op.alter_column('sample_oracles', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='探测规则记录ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sample_executions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='节点最后上报心跳或更新状态的时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sample_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='生成执行计划的时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sample_executions', 'error_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='如果系统自身级别抛出崩溃或异常超时，记录具体Traceback或摘要',
               existing_nullable=True)
    op.alter_column('sample_executions', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='完成判定及扫尾清理的时刻',
               existing_nullable=True)
    op.alter_column('sample_executions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='开始投递诱导指令的时刻',
               existing_nullable=True)
    op.alter_column('sample_executions', 'environment_ref',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='分配执行所关联的隔离容器或沙箱环境标识',
               existing_nullable=True)
    op.alter_column('sample_executions', 'entry_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='向Agent真实投递该用例的请求URL/抓包URL线索',
               existing_nullable=True)
    op.alter_column('sample_executions', 'work_dir',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='分配到沙箱机进行执行的物理工作目录',
               existing_nullable=True)
    op.alter_column('sample_executions', 'retry_no',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='当前记录属于第几次重试(首次默认0)',
               existing_nullable=False)
    op.alter_column('sample_executions', 'status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='执行的生命周期状态(pending, dispatching, executing, verifying, done, error等)',
               existing_nullable=False)
    op.alter_column('sample_executions', 'sample_id_ref',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='对应的官方测试样本库的实体ID',
               existing_nullable=False)
    op.alter_column('sample_executions', 'run_sample_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='映射关系ID(关联了具体的执行计划)',
               existing_nullable=False)
    op.alter_column('sample_executions', 'run_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='所属任务ID(冗余字段以便于大批量聚合查询)',
               existing_nullable=False)
    op.alter_column('sample_executions', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='执行记录主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sample_difficulty_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='统计数值最后刷新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sample_difficulty_stats', 'last_execution_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='该用例最近一次被触发使用的时间',
               existing_nullable=True)
    op.alter_column('sample_difficulty_stats', 'algorithm_version',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='计算当前统计维度所使用的衰减与算阶算法版本约定',
               existing_nullable=False)
    op.alter_column('sample_difficulty_stats', 'inferred_difficulty',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment=None,
               existing_comment='统计算法归一化后的相对防御难度指标量化分级',
               existing_nullable=False)
    op.alter_column('sample_difficulty_stats', 'safe_completion_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='成功防御的安全通过率',
               existing_nullable=False)
    op.alter_column('sample_difficulty_stats', 'harm_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               comment=None,
               existing_comment='根据上述指标计算出来的安全损害检出历史比率(反应其杀伤力)',
               existing_nullable=False)
    op.alter_column('sample_difficulty_stats', 'safe_completion_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='防御生效且依然完成了良性目标的次数记录',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sample_difficulty_stats', 'harm_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='历史以来成功使得被测端发生安全侵入/利用成功的次数累计',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sample_difficulty_stats', 'valid_execution_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='历史所有跑过该用例的累计有效运行次数记录',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sample_difficulty_stats', 'sample_id_ref',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='官方样本基准ID',
               existing_nullable=False)
    op.alter_column('run_samples', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='加入任务队列的时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('run_samples', 'order_no',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='如果在该任务中指定了样本编排执行顺序，记录其序号',
               existing_nullable=True)
    op.alter_column('run_samples', 'sample_id_ref',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='关联的基准测试样本的主键ID',
               existing_nullable=False)
    op.alter_column('run_samples', 'run_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='关联的测评任务ID',
               existing_nullable=False)
    op.alter_column('run_samples', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='记录主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('run_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='报告定稿完毕生成的最新归档时间',
               existing_nullable=True)
    op.alter_column('run_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='排队或创建开始生成的记录时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('run_reports', 'report_uri',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='生成的诸如PDF版本/归档富文本格式静态存储路径',
               existing_nullable=True)
    op.alter_column('run_reports', 'summary_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='雷达图信息：分类安全得分汇总大json及结构化建议摘要',
               existing_nullable=True)
    op.alter_column('run_reports', 'report_status',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='当前组装报告状态(如：generating, available, failed)',
               existing_nullable=False)
    op.alter_column('run_reports', 'run_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='映射具体的测试调起任务实体',
               existing_nullable=False)
    op.alter_column('run_reports', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='报告主键标识',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('risk_subtypes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录生成时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_subtypes', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否激活支持测算',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('risk_subtypes', 'sort_order',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='列表呈现时的排序支持',
               existing_nullable=True)
    op.alter_column('risk_subtypes', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='相关背景资料及评测目的要求',
               existing_nullable=True)
    op.alter_column('risk_subtypes', 'name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='具体诱骗或攻击类别名',
               existing_nullable=False)
    op.alter_column('risk_subtypes', 'code',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='子类唯一特征码(类目级别内唯一)',
               existing_nullable=False)
    op.alter_column('risk_subtypes', 'category_id',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='归属的一级风险大类ID',
               existing_nullable=False)
    op.alter_column('risk_subtypes', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='子类ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('risk_subtype_display_meta', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='资料最后更新归档日',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_subtype_display_meta', 'media',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='包含在富文本中所需的图片或视频演示材料(List<Dict>)',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('risk_subtype_display_meta', 'resources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='外部关联文件及文档引用(List<Dict>)',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('risk_subtype_display_meta', 'scenarios',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='典型的受影响业务场景罗列(List<str>)',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('risk_subtype_display_meta', 'highlights',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='提炼核心特质或难点以列表记录(List<str>)',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('risk_subtype_display_meta', 'full_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='全面的长篇幅 Markdown 富文本知识讲解',
               existing_nullable=True)
    op.alter_column('risk_subtype_display_meta', 'short_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='一句话精简业务概括描述',
               existing_nullable=True)
    op.alter_column('risk_subtype_display_meta', 'subtype_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='映射的一对一关联风险子类主键',
               existing_nullable=False)
    op.alter_column('risk_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最后更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('risk_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否有效',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('risk_categories', 'sort_order',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='前端UI展示或大屏呈现时的排序字段',
               existing_nullable=True)
    op.alter_column('risk_categories', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='更详细的描述信息',
               existing_nullable=True)
    op.alter_column('risk_categories', 'meaning',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='该大类的安全意义及考核目的标准解读',
               existing_nullable=True)
    op.alter_column('risk_categories', 'name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='分类规范名称(如：机密性泄露)',
               existing_nullable=False)
    op.alter_column('risk_categories', 'code',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='分类唯一代码',
               existing_nullable=False)
    op.alter_column('risk_categories', 'id',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='大类ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('risk_categories_id_seq'::regclass)"))
    op.alter_column('oracle_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='结果落盘时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('oracle_results', 'evaluator_version',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='判定当下所使用的预言机引擎版本，便于追溯算法一致性',
               existing_nullable=True)
    op.alter_column('oracle_results', 'evidence_ref',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='关联引用具体的判定依据线索，用于进一步排查',
               existing_nullable=True)
    op.alter_column('oracle_results', 'evidence_summary',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='若判定由于某种输出而命中，则摘录该段输出/总结',
               existing_nullable=True)
    op.alter_column('oracle_results', 'score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment=None,
               existing_comment='该评估器判定打出的0-1之间的小数分数',
               existing_nullable=True)
    op.alter_column('oracle_results', 'matched',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否命中规则所描述的状态 (如攻击是否成功)',
               existing_nullable=False)
    op.alter_column('oracle_results', 'oracle_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='对应所调用的具体预言机/规则探测器标识',
               existing_nullable=False)
    op.alter_column('oracle_results', 'sample_execution_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='其归属的当条样本执行上下文的主键',
               existing_nullable=False)
    op.alter_column('oracle_results', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='判定明细ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('execution_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='生成总结报告时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_summaries', 'final_label',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='打上的内部结果分类词(如：safe, hijacked, timeout, refused)',
               existing_nullable=True)
    op.alter_column('execution_summaries', 'summary_text',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='面向人类视角的该条测试行为全景综述总结评定',
               existing_nullable=True)
    op.alter_column('execution_summaries', 'harm_detected',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='测评平台是否探测了预期破坏/被诱攻击成功的指标发生',
               existing_nullable=False)
    op.alter_column('execution_summaries', 'task_completed',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Agent层面是否完成了用户本来的良性任务指派目标',
               existing_nullable=False)
    op.alter_column('execution_summaries', 'sample_execution_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='单次样本调度上下文映射键',
               existing_nullable=False)
    op.alter_column('execution_summaries', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='汇总评价ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('execution_artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录落盘上传完毕保存时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('execution_artifacts', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='附带的元信息(比如长宽、抓包包类描述等)',
               existing_nullable=True)
    op.alter_column('execution_artifacts', 'storage_uri',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='产物实体文件所存储的具体物理或对象存储URI',
               existing_nullable=False)
    op.alter_column('execution_artifacts', 'artifact_type',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='产物类型(如：screenshot, log, payload)',
               existing_nullable=False)
    op.alter_column('execution_artifacts', 'sample_execution_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='其归属的具体运行实体ID',
               existing_nullable=False)
    op.alter_column('execution_artifacts', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='副产物记录主键ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('dataset_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dataset_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('dataset_sources', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='详细描述',
               existing_nullable=True)
    op.alter_column('dataset_sources', 'name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='来源别名/展示名',
               existing_nullable=False)
    op.alter_column('dataset_sources', 'code',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='来源唯一编码',
               existing_nullable=False)
    op.alter_column('dataset_sources', 'id',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='来源主键ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('dataset_sources_id_seq'::regclass)"))
    op.alter_column('benchmark_samples', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='样本数据修因订立与排查修正发生的最后变动点',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('benchmark_samples', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='样本建档纳入时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('benchmark_samples', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='该基准样本是否仍然对外公开并纳入日常可用题库池',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('benchmark_samples', 'expected_safe_behavior',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='该场景下满分防御的预期理论应对行为要求描述',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'asset_type_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='测试用例拟破坏的核心资料或者被利用的虚拟资源标的特征类型',
               existing_nullable=True)
    op.alter_column('benchmark_samples', 'difficulty_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='最近一次通过后台批处理作业重算动态更新难度得分的时间',
               existing_nullable=True)
    op.alter_column('benchmark_samples', 'difficulty_score',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment=None,
               existing_comment='结合系统长线多次测评大盘通过率反向拟合生成的动态挑战难度系数(0-1)',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'difficulty_seed',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               comment=None,
               existing_comment='入库时基准所携带的初始默认人工预估难度权重',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'attack_level',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='静态评估该手法的注入技术隐蔽度及难度分级(1-3)',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'risk_level',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='静态评估的主观危险级别(1-3)',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'risk_subtype_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='该样本试图利用的安全漏洞精确二级分类ID',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'attack_delivery_type_id',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='注入方案及投寄技术类型关联',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'attacker_is_user',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='攻击者是否具有当前模拟用例受害者一第一人称控制权伪装身份',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'attacker_goal',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='攻击者隐藏在该请求背后的真实破坏目的',
               existing_nullable=True)
    op.alter_column('benchmark_samples', 'user_goal',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='用户的表面正常请求目标(用于掩护恶意攻击)',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'entry_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='向被测Agent发起实际请求需要解析注入的最核心入口投递文件路径',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'resource_path',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='存放其依赖运行的辅助沙箱文件/配置(如：隔离容器目录定义)位置',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'sample_name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='样本标题/自然语言称呼',
               existing_nullable=True)
    op.alter_column('benchmark_samples', 'sample_id',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='该来源数据集下声明的原始唯一标号(不与其他来源冲突)',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'dataset_source_id',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='归属的数据集来源标志ID',
               existing_nullable=False)
    op.alter_column('benchmark_samples', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='基准测试样本表本地主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('attack_delivery_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='记录创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attack_delivery_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('attack_delivery_types', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='该注入类型的技术详情或补充说明',
               existing_nullable=True)
    op.alter_column('attack_delivery_types', 'name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='注入手段展示名',
               existing_nullable=False)
    op.alter_column('attack_delivery_types', 'code',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='唯一特征编码',
               existing_nullable=False)
    op.alter_column('attack_delivery_types', 'id',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='注入手段主键ID',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('attack_delivery_types_id_seq'::regclass)"))
    op.alter_column('asset_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='创建的时间点',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('asset_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('asset_types', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='描述以及涉及的数据分级评定',
               existing_nullable=True)
    op.alter_column('asset_types', 'name',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='被保护资产官方学名',
               existing_nullable=False)
    op.alter_column('asset_types', 'code',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='类型编码规则(如：asset_credential)',
               existing_nullable=False)
    op.alter_column('asset_types', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='资产标的ID',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
